/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StackRouteImport } from './routes/stack'
import { Route as BoxRouteImport } from './routes/box'
import { Route as IndexRouteImport } from './routes/index'

const StackRoute = StackRouteImport.update({
  id: '/stack',
  path: '/stack',
  getParentRoute: () => rootRouteImport,
} as any)
const BoxRoute = BoxRouteImport.update({
  id: '/box',
  path: '/box',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/box': typeof BoxRoute
  '/stack': typeof StackRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/box': typeof BoxRoute
  '/stack': typeof StackRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/box': typeof BoxRoute
  '/stack': typeof StackRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/box' | '/stack'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/box' | '/stack'
  id: '__root__' | '/' | '/box' | '/stack'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BoxRoute: typeof BoxRoute
  StackRoute: typeof StackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/stack': {
      id: '/stack'
      path: '/stack'
      fullPath: '/stack'
      preLoaderRoute: typeof StackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/box': {
      id: '/box'
      path: '/box'
      fullPath: '/box'
      preLoaderRoute: typeof BoxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BoxRoute: BoxRoute,
  StackRoute: StackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
