/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SwitcherRouteImport } from './routes/switcher'
import { Route as StackRouteImport } from './routes/stack'
import { Route as SidebarRouteImport } from './routes/sidebar'
import { Route as ClusterRouteImport } from './routes/cluster'
import { Route as CenterRouteImport } from './routes/center'
import { Route as BoxRouteImport } from './routes/box'
import { Route as IndexRouteImport } from './routes/index'

const SwitcherRoute = SwitcherRouteImport.update({
  id: '/switcher',
  path: '/switcher',
  getParentRoute: () => rootRouteImport,
} as any)
const StackRoute = StackRouteImport.update({
  id: '/stack',
  path: '/stack',
  getParentRoute: () => rootRouteImport,
} as any)
const SidebarRoute = SidebarRouteImport.update({
  id: '/sidebar',
  path: '/sidebar',
  getParentRoute: () => rootRouteImport,
} as any)
const ClusterRoute = ClusterRouteImport.update({
  id: '/cluster',
  path: '/cluster',
  getParentRoute: () => rootRouteImport,
} as any)
const CenterRoute = CenterRouteImport.update({
  id: '/center',
  path: '/center',
  getParentRoute: () => rootRouteImport,
} as any)
const BoxRoute = BoxRouteImport.update({
  id: '/box',
  path: '/box',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/box': typeof BoxRoute
  '/center': typeof CenterRoute
  '/cluster': typeof ClusterRoute
  '/sidebar': typeof SidebarRoute
  '/stack': typeof StackRoute
  '/switcher': typeof SwitcherRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/box': typeof BoxRoute
  '/center': typeof CenterRoute
  '/cluster': typeof ClusterRoute
  '/sidebar': typeof SidebarRoute
  '/stack': typeof StackRoute
  '/switcher': typeof SwitcherRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/box': typeof BoxRoute
  '/center': typeof CenterRoute
  '/cluster': typeof ClusterRoute
  '/sidebar': typeof SidebarRoute
  '/stack': typeof StackRoute
  '/switcher': typeof SwitcherRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/box'
    | '/center'
    | '/cluster'
    | '/sidebar'
    | '/stack'
    | '/switcher'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/box'
    | '/center'
    | '/cluster'
    | '/sidebar'
    | '/stack'
    | '/switcher'
  id:
    | '__root__'
    | '/'
    | '/box'
    | '/center'
    | '/cluster'
    | '/sidebar'
    | '/stack'
    | '/switcher'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BoxRoute: typeof BoxRoute
  CenterRoute: typeof CenterRoute
  ClusterRoute: typeof ClusterRoute
  SidebarRoute: typeof SidebarRoute
  StackRoute: typeof StackRoute
  SwitcherRoute: typeof SwitcherRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/switcher': {
      id: '/switcher'
      path: '/switcher'
      fullPath: '/switcher'
      preLoaderRoute: typeof SwitcherRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stack': {
      id: '/stack'
      path: '/stack'
      fullPath: '/stack'
      preLoaderRoute: typeof StackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sidebar': {
      id: '/sidebar'
      path: '/sidebar'
      fullPath: '/sidebar'
      preLoaderRoute: typeof SidebarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cluster': {
      id: '/cluster'
      path: '/cluster'
      fullPath: '/cluster'
      preLoaderRoute: typeof ClusterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/center': {
      id: '/center'
      path: '/center'
      fullPath: '/center'
      preLoaderRoute: typeof CenterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/box': {
      id: '/box'
      path: '/box'
      fullPath: '/box'
      preLoaderRoute: typeof BoxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BoxRoute: BoxRoute,
  CenterRoute: CenterRoute,
  ClusterRoute: ClusterRoute,
  SidebarRoute: SidebarRoute,
  StackRoute: StackRoute,
  SwitcherRoute: SwitcherRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
